# Deployment: Gerencia as cópias do contêiner e garante que esteja sempre rodando.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-java-container
          image: natasha0600/todo-java-k8s:v1
          ports:
            - containerPort: 8080

# Service: Atua como Load Balancer e cria um endereço fixo para acesso.
---
apiVersion: v1
kind: Service
metadata:
  name: todo-list-service
spec:
  selector:
    app: todo-app
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer