# --- 1. Deployment: Gerencia as cópias do seu contêiner ---
# O Deployment garante que a aplicação esteja sempre rodando e define o número de réplicas.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-deployment
spec:
  replicas: 2 # Kubernetes manterá 2 cópias (pods) da sua API rodando
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-java-container
          # IMAGEM DO SEU DOCKER HUB:
          image: natasha0600/todo-java-k8s:v1
          ports:
            - containerPort: 8080 # A porta interna do Spring Boot

# --- 2. Service: Cria um endereço fixo para acessar o Deployment ---
# O Service atua como um Load Balancer para as 2 cópias do Deployment.
---
apiVersion: v1
kind: Service
metadata:
  name: todo-list-service
spec:
  selector:
    app: todo-app
  ports:
    - port: 8080         # A porta que você acessará fora do cluster
      targetPort: 8080   # A porta interna do seu contêiner
  type: LoadBalancer # Permite acessar a aplicação facilmente do seu PC